### ISSUE TITLE
Creating paste fails

### ISSUE THREAD

**Issue by modem7** [interaapps/pastefy#26]
Hey guys, 

Attempting to paste a rather long test paste (around 3000 lines), and it fails with some backend errors. 

```
today at 20:30:29SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
today at 20:30:29SLF4J: Defaulting to no-operation (NOP) logger implementation
today at 20:30:29SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
today at 20:30:30ADDED google as auth provider
today at 20:30:30Mar 02, 2022 8:30:30 PM org.javawebstack.httpserver.HTTPServer start
today at 20:30:30INFO: HTTP-Server started on port 80
today at 20:30:33AUTH EXCEPTION
today at 20:30:43AUTH EXCEPTION
today at 20:32:13AUTH EXCEPTION
today at 20:32:50AUTH EXCEPTION
today at 20:32:57AUTH EXCEPTION
today at 20:47:31AUTH EXCEPTION
today at 20:47:31AUTH EXCEPTION
today at 20:47:34AUTH EXCEPTION
today at 20:49:19com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 2501 path $.content
today at 20:49:19	at com.google.gson.Gson.fromJson(Gson.java:978)
today at 20:49:19	at com.google.gson.Gson.fromJson(Gson.java:928)
today at 20:49:19	at com.google.gson.Gson.fromJson(Gson.java:877)
today at 20:49:19	at com.google.gson.Gson.fromJson(Gson.java:848)
today at 20:49:19	at org.javawebstack.abstractdata.AbstractElement.fromJson(AbstractElement.java:178)
today at 20:49:19	at org.javawebstack.httpserver.Exchange.body(Exchange.java:75)
today at 20:49:19	at org.javawebstack.httpserver.router.RouteBinder$BindMapper.invoke(RouteBinder.java:229)
today at 20:49:19	at org.javawebstack.httpserver.router.RouteBinder$BindHandler.handle(RouteBinder.java:300)
today at 20:49:19	at org.javawebstack.httpserver.HTTPServer.execute(HTTPServer.java:339)
today at 20:49:19	at org.javawebstack.httpserver.HTTPServer$HttpHandler.handle(HTTPServer.java:415)
today at 20:49:19	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
today at 20:49:19	at org.eclipse.jetty.server.Server.handle(Server.java:516)
today at 20:49:19	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
today at 20:49:19	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
today at 20:49:19	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
today at 20:49:19	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
today at 20:49:19	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
today at 20:49:19	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
today at 20:49:19	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
today at 20:49:19	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
today at 20:49:19	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
today at 20:49:19	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
today at 20:49:19	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
today at 20:49:19	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
today at 20:49:19	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
today at 20:49:19	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
today at 20:49:19	at java.lang.Thread.run(Thread.java:748)
today at 20:49:19Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 2501 path $.content
today at 20:49:19	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562)
today at 20:49:19	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1030)
today at 20:49:19	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:814)
today at 20:49:19	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:663)
today at 20:49:19	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:684)
today at 20:49:19	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655)
today at 20:49:19	at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:866)
today at 20:49:19	at com.google.gson.Gson.fromJson(Gson.java:963)
today at 20:49:19	... 26 more
today at 20:49:30com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 2501 path $.content
today at 20:49:30	at com.google.gson.Gson.fromJson(Gson.java:978)
today at 20:49:30	at com.google.gson.Gson.fromJson(Gson.java:928)
today at 20:49:30	at com.google.gson.Gson.fromJson(Gson.java:877)
today at 20:49:30	at com.google.gson.Gson.fromJson(Gson.java:848)
today at 20:49:30	at org.javawebstack.abstractdata.AbstractElement.fromJson(AbstractElement.java:178)
today at 20:49:30	at org.javawebstack.httpserver.Exchange.body(Exchange.java:75)
today at 20:49:30	at org.javawebstack.httpserver.router.RouteBinder$BindMapper.invoke(RouteBinder.java:229)
today at 20:49:30	at org.javawebstack.httpserver.router.RouteBinder$BindHandler.handle(RouteBinder.java:300)
today at 20:49:30	at org.javawebstack.httpserver.HTTPServer.execute(HTTPServer.java:339)
today at 20:49:30	at org.javawebstack.httpserver.HTTPServer$HttpHandler.handle(HTTPServer.java:415)
today at 20:49:30	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
today at 20:49:30	at org.eclipse.jetty.server.Server.handle(Server.java:516)
today at 20:49:30	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
today at 20:49:30	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
today at 20:49:30	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
today at 20:49:30	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
today at 20:49:30	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
today at 20:49:30	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
today at 20:49:30	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
today at 20:49:30	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
today at 20:49:30	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
today at 20:49:30	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
today at 20:49:30	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
today at 20:49:30	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
today at 20:49:30	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
today at 20:49:30	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
today at 20:49:30	at java.lang.Thread.run(Thread.java:748)
today at 20:49:30Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 2501 path $.content
today at 20:49:30	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562)
today at 20:49:30	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1030)
today at 20:49:30	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:814)
today at 20:49:30	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:663)
today at 20:49:30	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:684)
today at 20:49:30	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655)
today at 20:49:30	at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:866)
today at 20:49:30	at com.google.gson.Gson.fromJson(Gson.java:963)
today at 20:49:30	... 26 more
today at 20:50:02AUTH EXCEPTION
today at 20:50:02AUTH EXCEPTION
today at 20:50:12com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 2585 path $.content
today at 20:50:12	at com.google.gson.Gson.fromJson(Gson.java:978)
today at 20:50:12	at com.google.gson.Gson.fromJson(Gson.java:928)
today at 20:50:12	at com.google.gson.Gson.fromJson(Gson.java:877)
today at 20:50:12	at com.google.gson.Gson.fromJson(Gson.java:848)
today at 20:50:12	at org.javawebstack.abstractdata.AbstractElement.fromJson(AbstractElement.java:178)
today at 20:50:12	at org.javawebstack.httpserver.Exchange.body(Exchange.java:75)
today at 20:50:12	at org.javawebstack.httpserver.router.RouteBinder$BindMapper.invoke(RouteBinder.java:229)
today at 20:50:12	at org.javawebstack.httpserver.router.RouteBinder$BindHandler.handle(RouteBinder.java:300)
today at 20:50:12	at org.javawebstack.httpserver.HTTPServer.execute(HTTPServer.java:339)
today at 20:50:12	at org.javawebstack.httpserver.HTTPServer$HttpHandler.handle(HTTPServer.java:415)
today at 20:50:12	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
today at 20:50:12	at org.eclipse.jetty.server.Server.handle(Server.java:516)
today at 20:50:12	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
today at 20:50:12	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
today at 20:50:12	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
today at 20:50:12	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
today at 20:50:12	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
today at 20:50:12	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
today at 20:50:12	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
today at 20:50:12	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
today at 20:50:12	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
today at 20:50:12	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
today at 20:50:12	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
today at 20:50:12	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
today at 20:50:12	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
today at 20:50:12	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
today at 20:50:12	at java.lang.Thread.run(Thread.java:748)
today at 20:50:12Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 2585 path $.content
today at 20:50:12	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562)
today at 20:50:12	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1030)
today at 20:50:12	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:814)
today at 20:50:12	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:663)
today at 20:50:12	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:684)
today at 20:50:12	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655)
today at 20:50:12	at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:866)
today at 20:50:12	at com.google.gson.Gson.fromJson(Gson.java:963)
today at 20:50:12	... 26 more
today at 20:50:20AUTH EXCEPTION
today at 20:50:28com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated escape sequence at line 1 column 2509 path $.content
today at 20:50:28	at com.google.gson.Gson.fromJson(Gson.java:978)
today at 20:50:28	at com.google.gson.Gson.fromJson(Gson.java:928)
today at 20:50:28	at com.google.gson.Gson.fromJson(Gson.java:877)
today at 20:50:28	at com.google.gson.Gson.fromJson(Gson.java:848)
today at 20:50:28	at org.javawebstack.abstractdata.AbstractElement.fromJson(AbstractElement.java:178)
today at 20:50:28	at org.javawebstack.httpserver.Exchange.body(Exchange.java:75)
today at 20:50:28	at org.javawebstack.httpserver.router.RouteBinder$BindMapper.invoke(RouteBinder.java:229)
today at 20:50:28	at org.javawebstack.httpserver.router.RouteBinder$BindHandler.handle(RouteBinder.java:300)
today at 20:50:28	at org.javawebstack.httpserver.HTTPServer.execute(HTTPServer.java:339)
today at 20:50:28	at org.javawebstack.httpserver.HTTPServer$HttpHandler.handle(HTTPServer.java:415)
today at 20:50:28	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
today at 20:50:28	at org.eclipse.jetty.server.Server.handle(Server.java:516)
today at 20:50:28	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
today at 20:50:28	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
today at 20:50:28	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
today at 20:50:28	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
today at 20:50:28	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
today at 20:50:28	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
today at 20:50:28	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
today at 20:50:28	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
today at 20:50:28	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
today at 20:50:28	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
today at 20:50:28	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
today at 20:50:28	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
today at 20:50:28	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
today at 20:50:28	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
today at 20:50:28	at java.lang.Thread.run(Thread.java:748)
today at 20:50:28Caused by: com.google.gson.stream.MalformedJsonException: Unterminated escape sequence at line 1 column 2509 path $.content
today at 20:50:28	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562)
today at 20:50:28	at com.google.gson.stream.JsonReader.readEscapeCharacter(JsonReader.java:1499)
today at 20:50:28	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1013)
today at 20:50:28	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:814)
today at 20:50:28	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:663)
today at 20:50:28	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:684)
today at 20:50:28	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655)
today at 20:50:28	at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:866)
today at 20:50:28	at com.google.gson.Gson.fromJson(Gson.java:963)
today at 20:50:28	... 26 more
today at 20:55:25com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated escape sequence at line 1 column 2509 path $.content
today at 20:55:25	at com.google.gson.Gson.fromJson(Gson.java:978)
today at 20:55:25	at com.google.gson.Gson.fromJson(Gson.java:928)
today at 20:55:25	at com.google.gson.Gson.fromJson(Gson.java:877)
today at 20:55:25	at com.google.gson.Gson.fromJson(Gson.java:848)
today at 20:55:25	at org.javawebstack.abstractdata.AbstractElement.fromJson(AbstractElement.java:178)
today at 20:55:25	at org.javawebstack.httpserver.Exchange.body(Exchange.java:75)
today at 20:55:25	at org.javawebstack.httpserver.router.RouteBinder$BindMapper.invoke(RouteBinder.java:229)
today at 20:55:25	at org.javawebstack.httpserver.router.RouteBinder$BindHandler.handle(RouteBinder.java:300)
today at 20:55:25	at org.javawebstack.httpserver.HTTPServer.execute(HTTPServer.java:339)
today at 20:55:25	at org.javawebstack.httpserver.HTTPServer$HttpHandler.handle(HTTPServer.java:415)
today at 20:55:25	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
today at 20:55:25	at org.eclipse.jetty.server.Server.handle(Server.java:516)
today at 20:55:25	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
today at 20:55:25	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
today at 20:55:25	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
today at 20:55:25	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
today at 20:55:25	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
today at 20:55:25	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
today at 20:55:25	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
today at 20:55:25	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
today at 20:55:25	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
today at 20:55:25	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
today at 20:55:25	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
today at 20:55:25	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
today at 20:55:25	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
today at 20:55:25	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
today at 20:55:25	at java.lang.Thread.run(Thread.java:748)
today at 20:55:25Caused by: com.google.gson.stream.MalformedJsonException: Unterminated escape sequence at line 1 column 2509 path $.content
today at 20:55:25	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562)
today at 20:55:25	at com.google.gson.stream.JsonReader.readEscapeCharacter(JsonReader.java:1499)
today at 20:55:25	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1013)
today at 20:55:25	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:814)
today at 20:55:25	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:663)
today at 20:55:25	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:684)
today at 20:55:25	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655)
today at 20:55:25	at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:866)
today at 20:55:25	at com.google.gson.Gson.fromJson(Gson.java:963)
today at 20:55:25	... 26 more
today at 20:55:47com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated escape sequence at line 1 column 2509 path $.content
today at 20:55:47	at com.google.gson.Gson.fromJson(Gson.java:978)
today at 20:55:47	at com.google.gson.Gson.fromJson(Gson.java:928)
today at 20:55:47	at com.google.gson.Gson.fromJson(Gson.java:877)
today at 20:55:47	at com.google.gson.Gson.fromJson(Gson.java:848)
today at 20:55:47	at org.javawebstack.abstractdata.AbstractElement.fromJson(AbstractElement.java:178)
today at 20:55:47	at org.javawebstack.httpserver.Exchange.body(Exchange.java:75)
today at 20:55:47	at org.javawebstack.httpserver.router.RouteBinder$BindMapper.invoke(RouteBinder.java:229)
today at 20:55:47	at org.javawebstack.httpserver.router.RouteBinder$BindHandler.handle(RouteBinder.java:300)
today at 20:55:47	at org.javawebstack.httpserver.HTTPServer.execute(HTTPServer.java:339)
today at 20:55:47	at org.javawebstack.httpserver.HTTPServer$HttpHandler.handle(HTTPServer.java:415)
today at 20:55:47	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
today at 20:55:47	at org.eclipse.jetty.server.Server.handle(Server.java:516)
today at 20:55:47	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
today at 20:55:47	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
today at 20:55:47	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
today at 20:55:47	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
today at 20:55:47	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
today at 20:55:47	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
today at 20:55:47	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
today at 20:55:47	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
today at 20:55:47	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
today at 20:55:47	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
today at 20:55:47	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
today at 20:55:47	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
today at 20:55:47	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
today at 20:55:47	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
today at 20:55:47	at java.lang.Thread.run(Thread.java:748)
today at 20:55:47Caused by: com.google.gson.stream.MalformedJsonException: Unterminated escape sequence at line 1 column 2509 path $.content
today at 20:55:47	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562)
today at 20:55:47	at com.google.gson.stream.JsonReader.readEscapeCharacter(JsonReader.java:1499)
today at 20:55:47	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1013)
today at 20:55:47	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:814)
today at 20:55:47	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:663)
today at 20:55:47	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:684)
today at 20:55:47	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655)
today at 20:55:47	at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:866)
today at 20:55:47	at com.google.gson.Gson.fromJson(Gson.java:963)
today at 20:55:47	... 26 more
```

Seems potentially related to #11 and #13

**Comment by JulianFun123** [comment]
Fixed bug with https://github.com/interaapps/pastefy/releases/tag/6.4.0 by setting the MySQL Column type to longtext. This will not allow infinite pastes, but much larger.
