### ISSUE TITLE
Github OAuth Authorization callback URL?

### ISSUE THREAD

**Issue by Optinux** [interaapps/pastefy#32]
What is Authorization callback URL that im supposed to use?
Not to be rude, but the current README is kinda lacking when it comes to selfhosting...

**Comment by Optinux** [comment]
speaking of which, how exactly am I supposed to edit the config as described in in the README? The location of a config is not specified and just editing the docker-compose with the new values doesnt work.

**Comment by JulianFun123** [comment]
The callback URL should be something like `https://{SERVER_NAME}/api/v2/auth/oauth2/github/callback`

**Comment by JulianFun123** [comment]
Can you send me the logs? There should be an exception

**Comment by Optinux** [comment]
Sorry for responding a year later but I haven't really gotten around getting Pastefy fixed. Even on the latest version and having created a new OAuth application, the same error still appears. Here's the log:
```java.lang.NullPointerException
	at de.interaapps.pastefy.auth.OAuth2Callback.handle(OAuth2Callback.java:21)
	at org.javawebstack.passport.strategies.oauth2.OAuth2Strategy.lambda$null$1(OAuth2Strategy.java:35)
	at org.javawebstack.httpserver.HTTPServer.execute(HTTPServer.java:339)
	at org.javawebstack.httpserver.HTTPServer$HttpHandler.handle(HTTPServer.java:415)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:750)
Exception in thread "Timer-0" org.javawebstack.orm.exception.ORMQueryException: Communications link failure
The last packet successfully received from the server was 27,228 milliseconds ago. The last packet sent successfully to the server was 27,229 milliseconds ago.
	at org.javawebstack.orm.query.Query.finalDelete(Query.java:369)
	at org.javawebstack.orm.query.Query.delete(Query.java:375)
	at de.interaapps.pastefy.Pastefy$2.run(Pastefy.java:296)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
