### ISSUE TITLE
Issue when trying to delete paste made with curl -F ... as admin

### ISSUE THREAD

**Issue by AWildLeon** [interaapps/pastefy#37]
Hey, I have an issue when trying to delete a Paste made with curl

```
java.lang.NullPointerException
        at de.interaapps.pastefy.controller.PasteController.deletePaste(PasteController.java:128)
        at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.javawebstack.httpserver.router.RouteBinder$BindMapper.invoke(RouteBinder.java:254)
        at org.javawebstack.httpserver.router.RouteBinder$BindHandler.handle(RouteBinder.java:300)
        at org.javawebstack.httpserver.HTTPServer.execute(HTTPServer.java:339)
        at org.javawebstack.httpserver.HTTPServer$HttpHandler.handle(HTTPServer.java:415)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.lang.Thread.run(Thread.java:750)
```

Edit: Self hosted Instance

**Comment by JulianFun123** [comment]
Did you send an access token when creating and deleting the paste?

**Comment by AWildLeon** [comment]
I did not send any token while creating, but i tryed deleting over the web interface while being logged in with an admin account and as an admin you should be able to delete those

**Comment by AWildLeon** [comment]
And even if I send a token it wont let me delete it
Command i used:
``curl -H "Authorization: Bearer [TOKEN]" -F f=@test https://paste.[Domain].de/``

**Comment by AWildLeon** [comment]
I know what's the error, it was fixed in master@bcf47fb37e1d0750ad4e4d5015dde5b1fdea6ef1
The user is not getting checked for null, because the docker image on docker hub is outdated

I verified that by building The project myself 

Could you please update the image?

**Comment by JulianFun123** [comment]
Okay that's weird. I remember creating a release (https://github.com/interaapps/pastefy/actions/runs/2592350132) but I'll create another one

**Comment by JulianFun123** [comment]
Okay now the merge request is released https://github.com/interaapps/pastefy/releases/tag/6.5.2

**Comment by AWildLeon** [comment]
Thanks,

Nice Little project

and Have a nice Day!
