### ISSUE TITLE
Paste private throws exception

### ISSUE THREAD

**Issue by Y0ngg4n** [interaapps/pastefy#45]
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Apr 25, 2023 3:28:23 PM org.javawebstack.httpserver.HTTPServer start
INFO: HTTP-Server started on port 80
de.interaapps.pastefy.exceptions.PastePrivateException
 at de.interaapps.pastefy.controller.PasteController.getPaste(PasteController.java:144)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.javawebstack.httpserver.router.RouteBinder$BindMapper.invoke(RouteBinder.java:254)
 at org.javawebstack.httpserver.router.RouteBinder$BindHandler.handle(RouteBinder.java:300)
 at org.javawebstack.httpserver.HTTPServer.execute(HTTPServer.java:339)
 at org.javawebstack.httpserver.HTTPServer$HttpHandler.handle(HTTPServer.java:415)
 at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
 at org.eclipse.jetty.server.Server.handle(Server.java:516)
 at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
 at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
 at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
 at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
 at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
 at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
 at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
 at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
 at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
 at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
 at java.lang.Thread.run(Thread.java:750)
```

**Comment by JulianFun123** [comment]
That will happen if a paste is private and you try to access it with another account. Currently there is an error in the frontend where you can set a paste to private when not logged in.

**Comment by Y0ngg4n** [comment]
I was logged in and tried to create a private paste and this happened.
