### ISSUE TITLE
Getting error when pasting large text

### ISSUE THREAD

**Issue by BorysVrublevskyi** [interaapps/pastefy#61]
On-site error message: `Error during posting the paste :(`

**Docker logs:**

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Jan 03, 2024 1:09:34 AM org.javawebstack.httpserver.HTTPServer start
INFO: HTTP-Server started on port 80
java.util.NoSuchElementException
        at java.util.ArrayDeque.removeFirst(ArrayDeque.java:285)
        at java.util.ArrayDeque.pop(ArrayDeque.java:522)
        at org.javawebstack.abstractdata.json.JsonParser.parseString(JsonParser.java:134)
        at org.javawebstack.abstractdata.json.JsonParser.parse(JsonParser.java:44)
        at org.javawebstack.abstractdata.json.JsonParser.parseObject(JsonParser.java:191)
        at org.javawebstack.abstractdata.json.JsonParser.parse(JsonParser.java:101)
        at org.javawebstack.abstractdata.json.JsonParser.parse(JsonParser.java:21)
        at org.javawebstack.abstractdata.AbstractElement.fromJson(AbstractElement.java:197)
        at org.javawebstack.httpserver.Exchange.body(Exchange.java:75)
        at org.javawebstack.httpserver.router.RouteBinder$BindMapper.invoke(RouteBinder.java:229)
        at org.javawebstack.httpserver.router.RouteBinder$BindHandler.handle(RouteBinder.java:300)
        at org.javawebstack.httpserver.HTTPServer.execute(HTTPServer.java:339)
        at org.javawebstack.httpserver.HTTPServer$HttpHandler.handle(HTTPServer.java:415)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.lang.Thread.run(Thread.java:750)

```

**docker-compose.yml**

```yaml
version: '3.9'

services:
  db:
    image: mariadb:11
    volumes:
    - dbvol:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: pastefy
      MYSQL_DATABASE: pastefy
      MYSQL_USER: pastefy
      MYSQL_PASSWORD: pastefy

  pastefy:
    image: interaapps/pastefy
    ports:
      # Host Post:Container Port. You only want to change the host port
      - "9999:80"
    depends_on:
    - db
    environment:
      HTTP_SERVER_PORT: 80
      HTTP_SERVER_CORS: "*"
      DATABASE_DRIVER: mysql
      DATABASE_NAME: pastefy
      DATABASE_USER: pastefy
      DATABASE_PASSWORD: pastefy
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      # JAVA_OPTS: "-Xmx512m -Xms256m"  # Adjust these values as needed
      # Set this to your domain
      SERVER_NAME: "http://pastefy.mydomain.local:9999"
      # There is INTERAAPPS, GOOGLE, GITHUB, DISCORD, TWITCH
      OAUTH2_PROVIDER_CLIENT_ID:
      OAUTH2_PROVIDER_CLIENT_SECRET:
      # Optional
      # PASTEFY_INFO_CUSTOM_LOGO=https://urltoimage
      # PASTEFY_INFO_CUSTOM_NAME=Custom Name
      # PASTEFY_INFO_CUSTOM_FOOTER=WEBSITE=https://example.org,SEPERATED BY COMMA=https://example.org
      # Requires login for read and creation of pastes
      PASTEFY_LOGIN_REQUIRED: false
      # Login-requirements for specific access types
      PASTEFY_LOGIN_REQUIRED_CREATE: false
      # This will disable the raw mode as well for browser users
      PASTEFY_LOGIN_REQUIRED_READ: false
      # Check the encryption checkbox by default
      PASTEFY_ENCRYPTION_DEFAULT: false
      # Requires every new account being accepted by an administrator
      PASTEFY_GRANT_ACCESS_REQUIRED: false
      # Allows /paste route listing all pastes
      PASTEFY_LIST_PASTES: true
      # Makes /app/stats public
      PASTEFY_PUBLIC_STATS: true
      # Enables public pastes section
      PASTEFY_PUBLIC_PASTES: true

volumes:
  dbvol:
```

**Comment by connexvtieu** [comment]
Issue was resolved for me when I upgraded the version of abstract-data in the pom.xml.

Try upgrading 1.0.3 to 1.0.6
